### ISSUE TITLE
ETL Visit Occurrence

### ISSUE THREAD

**Issue by aguynamedryan** [OHDSI/ETL-CMS#1]
visit_occurrences aren't yet generated by the ETL.

This is the most complicated table to ETL.  Employees of @OutcomesInsights (@claire-oi, @marc-outins, @jenniferduryea) are standing by to answer questions about this part of the ETL should you have any.

**Comment by ChristopheLambert** [comment]
These are generated in the latest release (1.0). Yeah they were complicated.
