### ISSUE TITLE
Make ETL run under Python 3.X

### ISSUE THREAD

**Issue by aguynamedryan** [OHDSI/ETL-CMS#10]
The original ETL was written with a few lines of code that only run under Python 2.x (mostly print statements that should be eliminated in #8).  

In my mind, the ETL should be running under Python 3.x, seeing as 3.x has gained relatively widespread adoption at this point and I don't believe there are any library-dependencies that require us to stick with 2.x

**Comment by chendaniely** [comment]
+1 to breaking Python 2.x support.  I believe there was also a comment from pycon this year about 2.x holding the community back.

**Comment by ChristopheLambert** [comment]
Every linux system has 2.7 installed, and now the code is all 2.7. By default 3.X is not installed in many Linux releases, which would force someone to have administrative privileges or compile Python 3.X from scratch.  I'd say leave it as is. I don't even see 3.X as a nice-to-have.

**Comment by ChristopheLambert** [comment]
Barring a volunteer who wants to fork the code and maintain a python 3.0 branch, I'm going to close out this issue.
