### ISSUE TITLE
List hardware and associated benchmarks

### ISSUE THREAD

**Issue by aguynamedryan** [OHDSI/ETL-CMS#13]
As part of the documentation we generate for the ETL, we should include some hardware requirements (if we hit any limits) along with approximate benchmarks for several of the hardware setups we run the ETL on.

**Comment by aguynamedryan** [comment]
I don't think the benchmarks have to be overly precise.  I just think it would be nice to know if the ETL takes 2 seconds, 2 minutes, 2 hours, or 2 days.

**Comment by ChristopheLambert** [comment]
We added some run times to the documentation -- it takes 45-60 minutes for 1/20th of the data -- about 14 hours to run the extract transform steps.
