### ISSUE TITLE
PEP8 Python Conventions

### ISSUE THREAD

**Issue by chendaniely** [OHDSI/ETL-CMS#14]
Suggest to slowly fix things to follow pep8 conventions as we slowly go spelunking.
We can worry about variable names being in all caps until we have the unit tests from #12 all created.

**Comment by aguynamedryan** [comment]
Would it behoove us to just reformat the code completely using some sort of pep8 auto-formatter?

**Comment by chendaniely** [comment]
I've never used it before, but [autopep8](https://github.com/hhatto/autopep8) sounds like a tool made for this

**Comment by aguynamedryan** [comment]
I'm primarily a Rubyist and don't know if I'd recognized "good Python" if I saw it.  @chendaniely, would you be willing to run the code through autopep8, and if the resulting code looks good to you, throw up a pull request and we'll incorporate the reformatted code.

**Comment by aguynamedryan** [comment]
For reference, [pep8 is described here](https://www.python.org/dev/peps/pep-0008/) in a link @chendaniely sent me.

I ran the code through autopep8 using various levels of "aggressive":
- [aggressive level 0](https://gist.github.com/aguynamedryan/7bf599f71b20fb88f6ba)
- [aggressive level 1](https://gist.github.com/aguynamedryan/9118c30a33723223b1c8)

Even with aggressive level set to 0, there are some changes that seem more annoying than anything else.  For instance, [I dislike this change](https://gist.github.com/aguynamedryan/7bf599f71b20fb88f6ba#file-foo-diff-L268) where the subscript is dropped to a second line.  Yuck.

Also, it doesn't seem to have changed the capitalization on any of the all caps variable names.

@chendaniely, I think, perhaps, your initial proposal of just fixing up the formatting as we spelunk and make changes is best.

**Comment by chendaniely** [comment]
That diff is way too much to handle and near impossible to debug if anything does break.

The subscript is dropped to a second line is because there's a (strict) 79 character line limit :p

**Comment by ChristopheLambert** [comment]
Sounds like this is a nice to have that we can live without.
