### ISSUE TITLE
omop_vocab_xref_0723.txt

### ISSUE THREAD

**Issue by sneakythr0ws** [OHDSI/ETL-CMS#19]
Hello!
Where I can find omop_vocab_xref_0723.txt?. Here is a [refenrence](https://github.com/OHDSI/ETL-CMS/blob/master/python_etl/CMS_SynPuf_ETL_CDM_v5.py#L322)

**Comment by ChristopheLambert** [comment]
I would recommend checking out the unm-improvements [branch](https://github.com/OHDSI/ETL-CMS/tree/unm-improvements), as dependency on this file was removed, and you can use the OMOP vocabulary files out of the box. The documentation on running the ETL has also been significantly extended, see [here](https://github.com/OHDSI/ETL-CMS/blob/unm-improvements/python_etl/README.md).  We hope to be committing some changes to the unm-improvements branch to make the ETL complete or near complete within the next week or so.

**Comment by ChristopheLambert** [comment]
This file is no longer part of the release.
