### ISSUE TITLE
srt-files not found

### ISSUE THREAD

**Issue by sneakythr0ws** [OHDSI/ETL-CMS#20]
I run [script from unm-improvements branch](https://github.com/OHDSI/ETL-CMS/tree/unm-improvements/python_etl) and found error

Script requires ".csv.srt" files. What is it? I disabled it [in this row](https://github.com/OHDSI/ETL-CMS/blob/unm-improvements/python_etl/FileControl.py#L294).

**Comment by ChristopheLambert** [comment]
Did you run all of the steps in the [README.md](https://github.com/OHDSI/ETL-CMS/blob/unm-improvements/python_etl/README.md) file, including downloading the data and setting up paths to where the data resides in the .env file?  The .srt files should be created by the script from the input data, and I suspect the input data path may have not been specified in the .env file.

**Comment by sneakythr0ws** [comment]
Yes. I generated .csv files by CMS_SynPuf_ETL_CDM_v5.py.
But I modified it to disable .srt check. The reason is that the script does not create srt-file
I tried master and unm-improvements

**Comment by ChristopheLambert** [comment]
Try the new master branch, and use the scripts/get_synpuf_files.py script to fetch the files. The creation of .srt files used to use system commands. We now create the .srt files directly with python code.

**Comment by ChristopheLambert** [comment]
I verified that the .srt files are properly created by the ETL for all 20 parts.
