### ISSUE TITLE
Carrier_Claims not found

### ISSUE THREAD

**Issue by sneakythr0ws** [OHDSI/ETL-CMS#21]
I run [script from unm-improvements branch](https://github.com/OHDSI/ETL-CMS/tree/unm-improvements/python_etl) and found error

Script looks for "DE1_0_2008_to_2010_Carrier_Claims_Sample_4.csv" file. ( not for DE1_0_2008_to_2010_Carrier_Claims_Sample_4A.csv or DE1_0_2008_to_2010_Carrier_Claims_Sample_4B.csv) and didn't found it.

I think it [here](https://github.com/OHDSI/ETL-CMS/blob/unm-improvements/python_etl/FileControl.py#L80)

**Comment by ChristopheLambert** [comment]
Please download the latest master branch. There was some irregularities with file naming at the CMS web site which we fixed in our code that downloads, sorts and merges files.
