### ISSUE TITLE
Letters in condition_source_concept_id

### ISSUE THREAD

**Issue by sneakythr0ws** [OHDSI/ETL-CMS#22]
I run [script from unm-improvements branch](https://github.com/OHDSI/ETL-CMS/tree/unm-improvements/python_etl) and found error

Condition_occurrence table has int condition_source_concept_id field. But script generates string value in this position (value has letters) of result csv-file. Source csv-file has no letters in condition_source_concept_id position

**Comment by ChristopheLambert** [comment]
Can you be more specific about what script you ran with what parameters?

**Comment by sneakythr0ws** [comment]
Here is a part of condition_occurence table csv-file. Its reulst of 
`python get_synpuf_files.py out 15`

CSV header

> condition_occurrence_id, person_id, condition_concept_id, condition_start_date, condition_end_date, condition_type_concept_id,stop_reason, provider_id, visit_occurrence_id, condition_source_value, condition_source_concept_id

As you can see, condition_source_concept_id field has value 872.72.
But in DDL it is INT

> 1,2,444058,2009-06-16,2009-06-16,38000230,,,327,872.72,872.72

Here is E878.1

> 4099,19,434547,2008-08-23,2008-08-27,38000200,,,168079,E878.1,E878.1

V letter

> 4164,19,4088290,2009-11-24,2009-11-24,38000230,,,177876,V45.71,V45.71

**Comment by ChristopheLambert** [comment]
We have since fixed this problem, but have not checked in the code yet.  The resulting data will cause additional errors at load time. We will keep you posted.

**Comment by ChristopheLambert** [comment]
The fix for this and many more problems have been committed.
