### ISSUE TITLE
CMS_SynPuf_ETL_CDM_v5.py uses in the inpatient visit type for all visit occurrences

### ISSUE THREAD

**Issue by sirpoovey** [OHDSI/ETL-CMS#26]
The Inpatient visit type is applied to all visit occurrences (9201).  Dropping this here as a reminder to myself or anyone else to make the quick fix.  Should also update the pre-compiled data files based on the fix.

https://github.com/OHDSI/ETL-CMS/blob/35d0c30664a6e677f1aac7cd69b0d4aa30235063/python_etl/CMS_SynPuf_ETL_CDM_v5.py#L1436

**Comment by ChristopheLambert** [comment]
I am rerunning the ETL -- hope to upload shortly.

**Comment by ChristopheLambert** [comment]
I have run the ETL and uploaded the pre-compiled data files. Thanks, @sirpoovey
