### ISSUE TITLE
columns mismatched in location table

### ISSUE THREAD

**Issue by rstarr7** [OHDSI/ETL-CMS#31]
In the location csv file, the data for the zip_code is in the county column position.  The zip code column position is null.

for example,

location_id,address_1,address_2,city,state,zip,county,location_source_value
1,,,,MO,,269500,26-95
2,,,,PA,,39230,39-230

**Comment by ChristopheLambert** [comment]
There are no zip codes in the data. The 5-digit codes are SSA county codes, where the first 2 digits are the state, and the next 3 digits are the county number.

**Comment by rstarr7** [comment]
That's great.  Thanks.

I was trying to decide whether to mention the fact that the zips and the states did not match up!

Richard Starr
Institute for People and Technology (IPaT) at Georgia Tech
(404) 491-1438
richard.starr@gatech.edumailto:richard.starr@gatech.edu

From: Christophe Lambert
Reply-To: OHDSI/ETL-CMS
Date: Monday, September 26, 2016 at 5:23 PM
To: OHDSI/ETL-CMS
Cc: Richard Starr, Author
Subject: Re: [OHDSI/ETL-CMS] columns mismatched in location table (#31)

There are no zip codes in the data. The 5-digit codes are SSA county codes, where the first 2 digits are the state, and the next 3 digits are the county number.
