### ISSUE TITLE
some case sensitive command issue in python-etl README file

### ISSUE THREAD

**Issue by opme** [OHDSI/ETL-CMS#36]
The command CMS_SynPuf_ETL_CDM_v5.py was CMS_SynP**UF**_ETL_CDM_v5.py in the python-etl README file which caused some confusion when trying to cut and paste commands from it.

**Comment by opme** [comment]
Pull request has been submitted

**Comment by ChristopheLambert** [comment]
Pull request incorporating your fixes was accepted.
