### ISSUE TITLE
SynPuf conversion using icd10 codes

### ISSUE THREAD

**Issue by opme** [OHDSI/ETL-CMS#40]
In 2015, Medicare switched over to using icd10 coding though a new SynPUF has not been provided.  Is there value in having a data set that uses icd10 codes instead of icd9?  

With some code I have written, I could pretty easily convert the omop Synpuf data from icd9 to icd10 and then shift the dates.   icd9 to icd10 can be one to many so the code could select a random icd10 code from the group.

Would there be interest in this?

I can see the need for 3 datasets:
-icd9 code dataset for pre 2015 data (direct convertion of SynPUF)
-icd10 code dataset for post 2015 data
-data the includes mixed icd9 and icd10 data based on the years the Medicare switched.

Goal is to allow researchers to test their code prior to getting the real data.

**Comment by cgreich** [comment]
Opme:

Why do you want ICD9 to ICD10? We are mapping to the Standard Concepts, and they are in SNOMED for Conditions. Anything I am missing?

**Comment by opme** [comment]
I am not an expert in this area but at least the CONDITION_SOURCE_VALUE (condition_occurrence) and PROCEDURE_SOURCE_VALUE (procedure_occurrence) codes are still in icd9 after the SynPuf ETL is run.

I think it will cause issues for application developers when there are mixed icd codes for a multi-year study?    At least for the use case I am developing to calculate surgeon complication rates the code only works when the data is not using mixed codes.  To make it easier to analyze this data, all codes would need to be converted to a common code.

Mike

**Comment by cgreich** [comment]
Yes, the source_value contains these values, but they should be the one actually in the source. Not some mapped alternative.

The mapping happens in the condition_concept_id and procedure_concept_id. Conditions are mapped to SNOMED, whether they are ICD-9-CM or ICD-10-CM. What you are trying to do is part of the OMOP standard. Use those.

**Comment by opme** [comment]
I see.  That is good news.  I will close this and test with some icd10 codes to make sure it is working.

**Comment by ChristopheLambert** [comment]
The ETL code is designed to transform the Synpuf data as it is. That is- the source data uses specific vocabularies, including ICD9. Stuffing ICD10 codes into ICD9 data columns and expecting it to convert makes no sense.  The Synpuf data is 2008-2010, before adoption of ICD10 in the US.
