### ISSUE TITLE
Update readme file for CPT VOCAB append

### ISSUE THREAD

**Issue by vickysam** [OHDSI/ETL-CMS#41]
File to update : https://github.com/OHDSI/ETL-CMS/blob/master/python_etl/README.md#3-download-cdmv5-vocabulary-files

Currently command to append CPT4 is:
>java -jar cpt4.jar

It should be:
>java -jar cpt4.jar <version = 4 or 5> <optional output file name>

**Comment by cgreich** [comment]
Will fix. Thanks, @vickysam.

**Comment by topspinj** [comment]
Athena instructions require you to pass in username and password of your UMLS account: 
```
java -Dumls-user=xxx -Dumls-password=xxx -jar cpt4.jar 5
```
Can you run it without?

**Comment by topspinj** [comment]
I get the following error when I run `java -jar cpt4.jar 5`: 
```
Error: Unable to initialize main class org.odhsi.utils.cpt.Application
Caused by: java.lang.NoClassDefFoundError: javax/xml/ws/WebServiceException
```
using Java v11. I'm not very familiar with Java, do you know what the issue might be?

**Comment by cgreich** [comment]
No, you need to have your UMLS license and credentials.
The machine needs access to the internet. Without any proxy gymnastics. Does it?

**Comment by topspinj** [comment]
Am still seeing that error (above) when I pass in my UMLS credentials.

**Comment by topspinj** [comment]
Update: The jar file isn't compatible with Java 11. After downgrading Java, I no longer get the error above. 

I think it would be useful to update the docs:
1. specify which Java version to use (version 10 or lower)
2. add UMLS credentials to jar command `java -Dumls-user=xxx -Dumls-password=xxx -jar cpt4.jar <version = 4 or 5>` (or  just use `bash cpt.sh`)
