### ISSUE TITLE
Error on Step 5 of Python ETL process

### ISSUE THREAD

**Issue by danielforsyth** [OHDSI/ETL-CMS#43]
When I run `python CMS_SynPuf_ETL_CDM_v5.py 0` on step 5 "Test ETL with DE_0 CMS test data" I get the following traceback

```
  File "CMS_SynPuf_ETL_CDM_v5.py", line 7, in <module>
    from constants import OMOP_CONSTANTS, OMOP_MAPPING_RECORD, BENEFICIARY_SUMMARY_RECORD, OMOP_CONCEPT_RECORD, OMOP_CONCEPT_RELATIONSHIP_RECORD
ImportError: cannot import name OMOP_CONSTANTS
```

Is this a problem with the env file?

**Comment by ChristopheLambert** [comment]
It could be the case. The .env file needs to be customized to the paths where your files are stored. Did you do that?

**Comment by danielforsyth** [comment]
Yep - All the paths are correct in the .env. Not sure whats causing this.

EDIT: Resolved it was a mistake on my end.
