### ISSUE TITLE
CMS RIF to OMOP ETL?

### ISSUE THREAD

**Issue by dckc** [OHDSI/ETL-CMS#45]
This doesn't support [RIF](https://www.resdac.org/cms-data/request/research-identifiable-files ), does it? Is there a repository nearby that does? I don't see one.

context: I'm working on CMS RIF to i2b2 (https://github.com/kumc-bmi/grouse) and considering going via OMOP.

cc @pbr6cornell @njgraham @rwaitman @mprittie

**Comment by markdanese** [comment]
No, it does not.  However, this should be a good starting point.  The attached poster might be somewhat helpful.
[AMIA OHDSI Medicare ETL v2.pdf](https://github.com/OHDSI/ETL-CMS/files/959256/AMIA.OHDSI.Medicare.ETL.v2.pdf)

**Comment by dckc** [comment]
I just discovered ETL code for PDESAF, MEDPAR, etc. in https://github.com/OHDSI/ETL-CDMBuilder/tree/master/bin/SEER/Definitions ; the `PATIENT_ID` column suggests it's not RIF, but it's pretty close.

In any case, this issue is clearly out of scope for this repo.
