### ISSUE TITLE
CMS ACO CCLF --> OMOP V5

### ISSUE THREAD

**Issue by schillil** [OHDSI/ETL-CMS#46]
[Version_18_CCLF_IP_Eff_April_2017.pdf](https://github.com/OHDSI/ETL-CMS/files/1073387/Version_18_CCLF_IP_Eff_April_2017.pdf)

ACO CCLF Information Packet Jan 2017, effective April 2017 - to support ETL work to OMOP v5

'issue' posted as new topic in the forum with reference to this git issue

**Comment by ChristopheLambert** [comment]
This repository is designed to ETL the SynPUF files. The forum issue seems inactive, and is asking for an ETL CMS ACO CCLF. Such an effort should have its own repository.
