### ISSUE TITLE
md5 sums don't match files - https://github.com/OHDSI/ETL-CMS/blob/master/python_etl/README.md

### ISSUE THREAD

**Issue by magic-lantern** [OHDSI/ETL-CMS#48]
I'm working on setting up a local copy of the OMOP SynPUF for testing and noticed that the MD5s show on the readme at https://github.com/OHDSI/ETL-CMS/blob/master/python_etl/README.md don't match the md5 of the files. This file on the ftp site matches what I get locally:

ftp://ftp.ohdsi.org/synpuf/1.0.1/md5sums.txt

The specific mismatches are (shown with what appears to be the correct md5 hash):

da0e310e7313e7b4894d1b1a15aee674  synpuf_1.zip
c1529ea8b4e4e092d0cdd2600ea61c75  visit_occurrence.csv.gz

The readme appears to have the old md5sums from ftp://ftp.ohdsi.org/synpuf/1.0.0/md5sums.txt for those two files.

**Comment by magic-lantern** [comment]
Forgot to ask - if you are ok with me doing a pull request to fix this, I'm happy to do so (assuming what I think is the solution is correct).

**Comment by ChristopheLambert** [comment]
Yes please feel free to fix.
Thanks,
Christophe

**Comment by magic-lantern** [comment]
Created pull request https://github.com/OHDSI/ETL-CMS/pull/49

**Comment by ChristopheLambert** [comment]
Pull request accepted.
