### ISSUE TITLE
Memory issue of steps 5 in ETL Script

### ISSUE THREAD

**Issue by Ratanr** [OHDSI/ETL-CMS#51]
Hi All,

I am executing the step 5 python ETL script and getting the below error.

![image](https://user-images.githubusercontent.com/21287124/37480507-cc162bb2-2855-11e8-8182-3f8e30adc98d.png)

when I tested the script with test data, it executed successfully but when I am running this on cSynpuf claims data I am having this issue.

I am running this on Intel i7-6600U CPU 2.81 GHz processor and 12 GB RAM. additionally, i have more than 150 GB space free on the drive.

Please let me know if someone has come across this issue while their implementation process and steps to resolve this.

Thanks in advance for your help.

Thanks,
Ratan

**Comment by Ratanr** [comment]
@ericaVoss @ChristopheLambert

**Comment by ericaVoss** [comment]
I have to leave this one to @ChristopheLambert

**Comment by ChristopheLambert** [comment]
Have you created a .env file, modeled off of .env.example.windows, correctly specifying all of the appropriate directories for input and output?

**Comment by Ratanr** [comment]
Yes, Christophe,

it is created and I am able to run and generate the test data. This issue is only happening when I am running synpuf claims data i.e DE_1-DE_20.

Thanks,
Ratan

**Comment by ChristopheLambert** [comment]
Can you print the entire traceback? The screenshot looks partial.

**Comment by Ratanr** [comment]
Hi Christophe,

here is the entire screenshot of the CMD, I cannot see any additional trackback.

![image](https://user-images.githubusercontent.com/21287124/37601356-3436fd86-2b60-11e8-9a0d-a0e5208e5d9d.png)


I tried to run this on a different system but still getting this issue. any help to resolve this issue would be grateful.

Thanks,
Ratan

**Comment by ChristopheLambert** [comment]
Is it possible you are using a 32-bit version of python that is maxing out the 2 or 4 GB limit of the memory space of 32-bit processes? In particular, if you installed 32-bit cygwin, I think the python that would be installed would also be 32-bit.

**Comment by Ratanr** [comment]
Hi Christophe,

yes, that was the issue. I installed 64 bit and it is working now. I thought I already have 64-bit version installed on my system but it was 32 bit.

Thanks a lot :)

Thanks,
Ratan

**Comment by ChristopheLambert** [comment]
Closing issue as it appears to be resolved.
