### ISSUE TITLE
Observation Periods are broken

### ISSUE THREAD

**Issue by aguynamedryan** [OHDSI/ETL-CMS#6]
The ETL is generating observation periods, but according to the original author, they seem to be incorrect.  I have no further details.

**Comment by ChristopheLambert** [comment]
In the latest release (1.0), we set the observation_period_start_date to the date of the first event seen for a patient, and the observation_period_end_date to the last event seen for a patient. This was a compromise in that we do not know from the data the actual dates of enrollment, only how many months out of a given year the patient was covered by one or more insurance plans.

**Comment by ChristopheLambert** [comment]
I am going to close this out, as I think we have fixed any earlier problems with observational periods, and we have done the best approximation we can per my previous comment.
