### ISSUE TITLE
missing 'DE1_0_2010_Beneficiary_Summary_File_Sample_1.zip'

### ISSUE THREAD

**Issue by yuna12** [OHDSI/ETL-CMS#62]
Hi,

I download the SynPUF data in CMS.

However, I can't download the file [DE1.0 Sample 1 2010 Beneficiary Summary File (ZIP)].
This file is linked to sample 20 not sample 1.
https://www.cms.gov/Research-Statistics-Data-and-Systems/Downloadable-Public-Use-Files/SynPUFs/Downloads/DE1_0_2010_Beneficiary_Summary_File_Sample_20.zip

Is there a way to access and download this file?

Thanks,
Yuna

**Comment by ChristopheLambert** [comment]
Isn't it this file: https://www.cms.gov/Research-Statistics-Data-and-Systems/Downloadable-Public-Use-Files/SynPUFs/Downloads/DE1_0_2008_Beneficiary_Summary_File_Sample_1.zip

Found on this page: https://www.cms.gov/Research-Statistics-Data-and-Systems/Downloadable-Public-Use-Files/SynPUFs/DESample01

**Comment by yuna12** [comment]
Thank you for your answer.
But I need '2010' not '2008'. TT

**Comment by ChristopheLambert** [comment]
I found a copy of the file from when we developed the ETL. It is attached here:
[DE1_0_2010_Beneficiary_Summary_File_Sample_1.zip](https://github.com/OHDSI/ETL-CMS/files/4932398/DE1_0_2010_Beneficiary_Summary_File_Sample_1.zip)

**Comment by yuna12** [comment]
OMG.. I thought I couldn't find it... 
Thank you very much.

**Comment by ChristopheLambert** [comment]
You are most welcome.
