### ISSUE TITLE
Downloading final data

### ISSUE THREAD

**Issue by pauloust** [OHDSI/ETL-CMS#64]
Hi, 

I tried to download the processed data from your FTP link and the Google drive but neither of them are working. Is there any other option to get the data ? 

Thanks.

Paul L

**Comment by jeff-m-sullivan** [comment]
This seems to be a duplicate of #63 and I believe both should be closed as **wontfix** based on the response there.

@pauloust PR #65 should fix the last remaining issue with downloading the CMS data from their website, so you should be able to run the entire process yourself. I just completed it a few weeks ago and everything seems to be in working order.
