### ISSUE TITLE
Incorrect URL to one source Synpuf file

### ISSUE THREAD

**Issue by schuemie** [OHDSI/ETL-CMS#65]
On the [CMS website](https://www.cms.gov/Research-Statistics-Data-and-Systems/Downloadable-Public-Use-Files/SynPUFs/DESample01), the 2010 Beneficiary Summary file of sample 1 has an incorrect name. It is called `DE1_0_2010_Beneficiary_Summary_File_Sample_20.zip`, but the Python script expects it to be called `DE1_0_2010_Beneficiary_Summary_File_Sample_1.zip` (which would make more sense since it is sample number 1, not 20).

Because of this, the Python script throws an error when trying to download the first sample. 

A simple workaround is:
1. Use the script to download the first sample, and watch it throw the error at the last file.
2. Manually download and unzip the missing file.
3. Use the script to download the other 19 samples without issue.

It would be nice if the script was modified to deal with this, but I suspect not many people will be working on this repo anymore.

**Comment by jeff-m-sullivan** [comment]
I've reached out to ResDAC to ask them about this. Will update here if I get a reply.

**Comment by ckrusemd** [comment]
Any news from ResDAC regarding this?

**Comment by jeff-m-sullivan** [comment]
I've learned that it's not something they maintain. I am trying to figure out who is responsible, but so far no luck.

**Comment by schuemie** [comment]
Maybe just implement a workaround in the script?

**Comment by schuemie** [comment]
Thanks!
